name: ColinWRoy
favicon: null
layout_spectrum: 0.7007169
typography_spectrum: 0.04141565482132137
title: ColinWRoy
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7580958311446011
  lightness: 0.1935484
  saturation: 0.3512545
  rhythmicContrast: 0.4516129
purpose: []
