name: ColinWRoy
favicon: null
layout_spectrum: 0.3393293786793947
typography_spectrum: 0.04141565482132137
title: ColinWRoy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7580958311446011
  lightness: 0.32285961881279945
  saturation: 0.1121941888704896
  rhythmicContrast: 0.741415427532047
purpose: []
